contactapp/urls.py
from django.urls import path
from . import views
app_name = 'contactapp'
urlpatterns = [

    path('', views.home,name='home'),
    path('movie/<int:movie_id>', views.detail, name='detail'),
    path('add/', views.add_movie, name='add_movie'),
    path('update/<int:id>/', views.update,name='update'),
    path('delete/<int:id>/', views.delete,name='delete')

]

contactproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('contactapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

contactapp/models.py
from django.db import models


# Create your models here.
class Movie(models.Model):
    name = models.CharField(max_length=250)
    desc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to='gallery', null=True,blank=True)

    def __str__(self):
        return self.name

contactapp/forms.py
from django import forms
from .models import Movie


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['name', 'desc', 'img', 'year']

contactapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from .forms import MovieForm
from .models import Movie


# Create your views here.
def home(request):
    movie = Movie.objects.all()
    contex = {
        'movie_list': movie
    }
    return render(request, 'index.html', contex)


def detail(request, movie_id):
    movie = Movie.objects.get(id=movie_id)
    return render(request, 'detail.html', {'movie': movie})


def add_movie(request):
    if request.method == "POST":
        name = request.POST.get('name', )
        desc = request.POST.get('desc', )
        year = request.POST.get('year')
        img = request.FILES['img']
        movie = Movie(name=name, desc=desc, year=year, img=img)
        movie.save()
    return render(request, 'add.html')


def update(request, id, ):
    movie = Movie.objects.get(id=id)
    form = MovieForm(request.POST or None,  instance=Movie)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('/')
    return render(request, 'edit.html', {'form': form, 'movie': movie})


def delete(request, id):
    if request.method == 'POST':
        movie = Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request, 'delete.html')

templates/add.html
{% extends 'base.html'%}
{% block body %}

<form method="POST" enctype="multipart/form-data">
{% csrf_token %}
  <input type="text" name="name" placeholder="Enter your movie name">
  <input type="text" name="desc" placeholder="Enter the movie description">
  <input type="text" name="year" placeholder="Enter your movie year">
  <input type="file" name="img" >
  <input type="submit" >


</form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
     online movie store

  </a>
    <div>
 <a class="btn btn-warning" href="{% url 'contactapp:add_movie'  %}"> ADD</a><br>
    </div>

</nav>
{% block body %}
{% endblock %}
</body>
</html>

templates/delete.html
<form method="post">

    {% csrf_token %}
    Are you want to delete the movie?
    <input type='submit'>
</form>

templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container" xmlns="http://www.w3.org/1999/html">
<div class="row">
    <div class="col-md-6">
        <img src="{{movie.img.url}}" width="300" height="300">
    </div>
<div class="col-md-6">
    <h6>{{movie.name}}</h6>
    <h6>{{movie.desc}}</h6>
    <h6>{{movie.year}}</h6>
    <a class="btn btn-warning" href="{% url 'contactapp:update' movie.id  %}"> Update </a><br>
    <a class="btn btn-danger"  href="{% url 'contactapp:delete' movie.id  %}"> Delete </a><br>
</div>

    </div>

</div>
{% endblock %}

templates/edit.html
<div class="container">

<form method="post">
    {% csrf_token %}
     {{ form.as_p }}
    <input type="submit" value="submit" />
</form>
    </div>

templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        {% for i in movie_list %}
<div class="col-md=3">
<div class="card" style="width: 18rem;">
  <img src="{{i.img.url}}" class="card-img-top" alt="..." width="100px" height="250px">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.desc}}</p>
    <a href="{% url 'contactapp:detail' i.id %}" class="btn btn-primary">View Details</a>
  </div>
</div>
     </div>
       {% endfor %}
    </div>
</div>

{% endblock %}